version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    networks:
      - gestion-alquiler-net

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - gestion-alquiler-net

  gestion-alquiler-api:
    container_name: gestion-alquiler-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - gestion-alquiler-net

networks:
  gestion-alquiler-net:
    driver: bridge

volumes:
  mongo-data:
